import {existsSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, relative, resolve} from 'node:path';
import ts from 'typescript';

type Prop = {name: string; type: string; optional: boolean};
type PublicInterface = {
  name: string;
  extends: string[];
  props: Prop[];
  source: string;
};
type PackageAPI = {package: string; interfaces: PublicInterface[]};

const repository = resolve(import.meta.dir, '..');
const packages: Array<{package: string; files: string[]; include?: Set<string>}> = [
  {
    package: '@incld/react',
    files: [
      'packages/react/src/provider.tsx',
      'packages/react/src/primitives.tsx',
    ],
    include: new Set(['IncldThemeVariables', 'IncldAppearance']),
  },
  {
    package: '@incld/react-schedules',
    files: [
      'packages/react-schedules/src/ScheduleComposer.tsx',
      'packages/react-schedules/src/components.tsx',
    ],
    include: new Set(['ScheduleComposerSlots']),
  },
  {
    package: '@incld/react-approvals',
    files: ['packages/react-approvals/src/components.tsx'],
  },
  {
    package: '@incld/react-bulk',
    files: ['packages/react-bulk/src/components.tsx'],
  },
  {
    package: '@incld/react-audit',
    files: ['packages/audit/src/components.tsx'],
  },
];

function compact(value: string) {
  return value.replace(/\s+/g, ' ').trim();
}

function exported(node: ts.InterfaceDeclaration) {
  return node.modifiers?.some(modifier => modifier.kind === ts.SyntaxKind.ExportKeyword) === true;
}

function propertyName(member: ts.PropertySignature, source: ts.SourceFile) {
  if (!member.name) return '';
  return compact(member.name.getText(source)).replace(/^['"]|['"]$/g, '');
}

function extract(file: string, explicitlyIncluded: Set<string> = new Set()): PublicInterface[] {
  const absolute = resolve(repository, file);
  const sourceText = readFileSync(absolute, 'utf8');
  const source = ts.createSourceFile(absolute, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const result: PublicInterface[] = [];

  source.forEachChild(node => {
    if (!ts.isInterfaceDeclaration(node) || !exported(node)) return;
    const name = node.name.text;
    if (!name.endsWith('Props') && !explicitlyIncluded.has(name)) return;

    result.push({
      name,
      extends: (node.heritageClauses ?? []).flatMap(clause =>
        clause.types.map(type => compact(type.getText(source))),
      ),
      props: node.members
        .filter(ts.isPropertySignature)
        .map(member => ({
          name: propertyName(member, source),
          type: compact(member.type?.getText(source) ?? 'unknown'),
          optional: Boolean(member.questionToken),
        }))
        .filter(prop => prop.name !== ''),
      source: `${file}:${source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1}`,
    });
  });

  return result;
}

const api: PackageAPI[] = packages.map(entry => ({
  package: entry.package,
  interfaces: entry.files
    .flatMap(file => extract(file, entry.include))
    .sort((left, right) => left.name.localeCompare(right.name)),
}));

const json = `${JSON.stringify({schemaVersion: 1, packages: api}, null, 2)}\n`;
const markdownLines = [
  '# Generated React component prop reference',
  '',
  '> Generated by `scripts/generate-react-api.ts` from exported TypeScript declarations. Do not edit by hand.',
  '',
];

for (const entry of api) {
  markdownLines.push(`## ${entry.package}`, '');
  for (const item of entry.interfaces) {
    markdownLines.push(`### ${item.name}`, '');
    if (item.extends.length) markdownLines.push(`Extends: \`${item.extends.join(', ')}\``, '');
    markdownLines.push(`Source: \`${item.source}\``, '');
    markdownLines.push('| Prop | Type | Required |', '| --- | --- | --- |');
    if (!item.props.length) markdownLines.push('| — | — | — |');
    for (const prop of item.props) {
      const type = prop.type.replaceAll('|', '\\|').replaceAll('`', '\\`');
      markdownLines.push(`| \`${prop.name}\` | \`${type}\` | ${prop.optional ? 'No' : 'Yes'} |`);
    }
    markdownLines.push('');
  }
}
const markdown = `${markdownLines.join('\n').trim()}\n`;

const outputs = new Map([
  [resolve(repository, 'docs/generated/react-component-props.json'), json],
  [resolve(repository, 'docs/generated/react-component-props.md'), markdown],
]);
const check = process.argv.includes('--check');
const drift: string[] = [];

for (const [path, content] of outputs) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) drift.push(relative(repository, path));
  } else {
    mkdirSync(dirname(path), {recursive: true});
    writeFileSync(path, content);
  }
}

if (drift.length) {
  throw new Error(`Generated React API documentation is stale: ${drift.join(', ')}. Run bun run docs:generate.`);
}

if (!check) console.log(`Generated ${outputs.size} React API documentation artifacts.`);
